import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Doctor Appointment App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main style={{ paddingTop: '65px', paddingBottom: '60px', height: 'auto' }}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
